name: todo
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:       # Required for every Flutter project
    sdk: flutter # Required for every Flutter project
  flutter_localizations: # Required to enable localization
    sdk: flutter         # Required to enable localization
  get: ^4.6.1
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  get_storage: ^2.0.3
  shared_preferences: ^2.0.6
  timezone: ^0.9.4

  cupertino_icons: ^1.0.8 # Only required if you use Cupertino (iOS style) icons
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  date_picker_timeline: ^1.2.6
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter # Required for a Flutter project that includes tests

  flutter_lints: ^5.0.0 # Contains a set of recommended lints for Flutter code
  flutter_launcher_icons: ^0.14.1 # Required to generate custom app icons

flutter:

  uses-material-design: true # Required if you use the Material icon font

  generate: true # Enables generation of localized strings from arb files

  assets:  # Lists assets, such as image files
    - images/
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/logo.webp"
  windows:
    generate: true
    image_path: "images/logo.webp"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/logo.webp"

  # fonts:              
    # - family: Schyler
      # fonts:
        # - asset: fonts/Schyler-Regular.ttf
        # - asset: fonts/Schyler-Italic.ttf
          # style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700